#!/usr/bin/env node
// Copies svgdom's pure geometry modules into src/geometry/vendor/.
//
// svgdom's package.json `exports` field exposes only the package root, so these
// modules cannot be deep-imported. They are pure maths over (nodeName,
// getAttribute, childNodes) with no dependency on svgdom's own DOM classes, so
// vendoring them lets us drive them from jsdom nodes instead.
//
// Re-run after bumping svgdom, then run the geometry tests.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(root, 'node_modules', 'svgdom');
const OUT = path.join(root, 'src', 'geometry', 'vendor');

// Flattened: every module lands in one directory, so imports become './x.js'.
const MODULES = [
  'src/utils/pathUtils.js',
  'src/utils/PointCloud.js',
  'src/utils/regex.js',
  'src/utils/NodeIterator.js',
  'src/utils/objectCreationUtils.js',
  'src/other/Box.js',
  'src/other/Point.js',
  'src/dom/svg/SVGMatrix.js',
  'src/dom/svg/SVGPoint.js',
  'src/dom/NodeFilter.js',
];

const version = JSON.parse(readFileSync(path.join(SRC, 'package.json'), 'utf8')).version;

const banner = (file) => `// Vendored from svgdom@${version} (${file}) — MIT.
// Copyright (c) 2017-2023 Ulrich-Matthias Schäfer. See src/geometry/vendor/LICENSE.
// Generated by scripts/vendor-svgdom.mjs — do not edit by hand.
`;

mkdirSync(OUT, { recursive: true });

// Some vendored files carry local bug fixes (search for "PATCHED"). Overwriting
// them silently would reintroduce upstream bugs we have already diagnosed, so
// refuse unless --force and say exactly what would be lost.
const PATCH_MARKER = 'PATCHED (not upstream svgdom)';
const force = process.argv.includes('--force');
const patched = MODULES.filter((rel) => {
  const dest = path.join(OUT, path.basename(rel));
  return existsSync(dest) && readFileSync(dest, 'utf8').includes(PATCH_MARKER);
});

if (patched.length && !force) {
  console.error('Refusing to overwrite locally patched files:');
  for (const rel of patched) console.error(`  ${path.basename(rel)}`);
  console.error(
    '\nRe-run with --force, then re-apply each patch and run the geometry tests.\n' +
      'Known local fixes:\n' +
      '  pathUtils.js  Arc.getCloud() — upstream returns rx as the vertical extent\n' +
      '                for a half-ellipse, making mermaid cylinder nodes ~61px too tall.'
  );
  process.exit(1);
}

for (const rel of MODULES) {
  let code = readFileSync(path.join(SRC, rel), 'utf8');
  // Flatten every relative import to a sibling in this directory.
  code = code.replace(
    /from\s+'(\.\.?\/[^']*\/)?([A-Za-z0-9_]+\.js)'/g,
    (_m, _dir, file) => `from './${file}'`
  );
  writeFileSync(path.join(OUT, path.basename(rel)), banner(rel) + code);
}

copyFileSync(path.join(SRC, 'LICENSE.txt'), path.join(OUT, 'LICENSE'));

console.log(`Vendored ${MODULES.length} modules from svgdom@${version} into src/geometry/vendor/`);
